site_index:
    path:     /
    defaults: { _controller: ArmyDataBundle:Default:index }
login:
    path:     /login/
    defaults: { _controller: ArmyDataBundle:Security:login }
login_check:
    path: /login_check
logout:
    path: /logout
unit_index:
    path:   /unit/
    defaults: { _controller: ArmyDataBundle:Unit:index }
unit_add:
    path:   /edit/add_unit
    defaults: { _controller: ArmyDataBundle:Unit:add }
unit_show:
    path:     /unit/show_unit/{id}
    defaults: { _controller: ArmyDataBundle:Unit:show }
unit_edit:
    path:     /edit/edit_unit/{id}
    defaults: { _controller: ArmyDataBundle:Unit:edit }
unit_delete:
    path:     /edit/delete_unit/{id}
    defaults: { _controller: ArmyDataBundle:Unit:delete }