<?php

namespace ArmyDataBundle\Repository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCollect ($unit){
        $em = $this->getEntityManager();

        $consulta = $em->createQuery('
            SELECT u, w
            FROM ArmyDataBundle:Unit u JOIN u.weapons w
            WHERE u.id = :id
        ');
        $consulta->setParameter('id', $unit);

        return $consulta->getResult();
    }
}
